In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/avelareliandro/analise-exploratoria-de-dados-estatisticos/refs/heads/main/dados_Imobiliario.csv"
pd.read_csv(url)

      Tipo;Bairro;Quartos;Vagas;Suites;Area;Valor;Condominio;IPTU
0              Quitinete;Copacabana;1;0;0;40;1700;500;60
1                  Casa;Jardim Botânico;2;0;1;100;7000;;
2      Conjunto Comercial/Sala;Barra da Tijuca;0;4;0;...
3                 Apartamento;Centro;1;0;0;15;800;390;20
4             Apartamento;Higienópolis;1;0;0;48;800;230;
...                                                  ...
32955               Quitinete;Centro;0;0;0;27;800;350;25
32956       Apartamento;Jacarepaguá;3;1;2;78;1800;800;40
32957  Apartamento;São Francisco Xavier;2;1;0;48;1400...
32958              Apartamento;Leblon;2;0;0;70;3000;760;
32959  Conjunto Comercial/Sala;Centro;0;0;0;250;6500;...

[32960 rows x 1 columns]

In [3]:
dados = pd.read_csv(url)

In [4]:
dados = pd.read_csv(url, sep=";")
# O separador é o ponto e vírgula, pois os dados estão separados por esse caractere.
dados.head()
# O método head() é utilizado para exibir as primeiras linhas do DataFrame, permitindo uma visualização rápida dos dados.
dados.info()
# O método info() fornece informações sobre o DataFrame, como o número de entradas, colunas, tipos de dados e valores nulos.
dados.describe()
# O método describe() gera estatísticas descritivas para as colunas numéricas do DataFrame, como média, desvio padrão, valores mínimos e máximos, entre outros.
dados.describe(include="all")
# O método describe() com o parâmetro include="all" inclui estatísticas descritivas para todas as colunas, incluindo as categóricas.
dados["Valor"].mean()
# O método mean() calcula a média da coluna "Valor", que representa o preço dos imóveis.
dados["Valor"].median()
# O método median() calcula a mediana da coluna "Valor", que é o valor central quando os dados estão ordenados.
dados["Valor"].mode()   
# O método mode() retorna o valor mais frequente na coluna "Valor". Se houver mais de um valor com a mesma frequência, ele retornará todos eles.
dados["Valor"].min()
# O método min() retorna o valor mínimo da coluna "Valor", ou seja, o preço mais baixo dos imóveis.
dados["Valor"].max()
# O método max() retorna o valor máximo da coluna "Valor", ou seja, o preço mais alto dos imóveis.
dados["Valor"].std()
# O método std() calcula o desvio padrão da coluna "Valor", que é uma medida de dispersão dos dados em relação à média.
dados["Valor"].var()
# O método var() calcula a variância da coluna "Valor", que é outra medida de dispersão dos dados em relação à média.
dados["Valor"].quantile(0.25)       
# O método quantile(0.25) retorna o primeiro quartil (Q1) da coluna "Valor", que é o valor abaixo do qual 25% dos dados estão localizados.
dados["Valor"].quantile(0.5)
# O método quantile(0.5) retorna o segundo quartil (Q2) ou mediana da coluna "Valor", que é o valor abaixo do qual 50% dos dados estão localizados.
dados["Valor"].quantile(0.75)
# O método quantile(0.75) retorna o terceiro quartil (Q3) da coluna "Valor", que é o valor abaixo do qual 75% dos dados estão localizados.
dados["Valor"].quantile(0.95)
# O método quantile(0.95) retorna o percentil 95 da coluna "Valor", que é o valor abaixo do qual 95% dos dados estão localizados.
type(dados)
# O comando type() é utilizado para verificar o tipo do objeto "dados", que é um DataFrame do pandas.
dados.shape
# O atributo shape retorna uma tupla com o número de linhas e colunas do DataFrame
dados[["Valor", "Quartos"]]
# O comando dados[["Valor", "Quartos"]] seleciona as colunas "Valor" e "Quartos" do DataFrame, retornando um novo DataFrame contendo apenas essas duas colunas.

#

<class 'pandas.DataFrame'>
RangeIndex: 32960 entries, 0 to 32959
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tipo        32960 non-null  str
 1   Bairro      32960 non-null  str
 2   Quartos     32960 non-null  int64
 3   Vagas       32960 non-null  int64
 4   Suites      32960 non-null  int64
 5   Area        32960 non-null  int64
 6   Valor       32943 non-null  float64
 7   Condominio  28867 non-null  float64
 8   IPTU        22723 non-null  float64
dtypes: float64(3), int64(4), str(2)
memory usage: 2.3 MB

        Valor  Quartos
0      1700.0        1
1      7000.0        2
2      5200.0        0
3       800.0        1
4       800.0        1
...       ...      ...
32955   800.0        0
32956  1800.0        3
32957  1400.0        2
32958  3000.0        2
32959  6500.0        0

[32960 rows x 2 columns]